# Generated by Django 6.0.6 on 2026-06-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_number'], name='idx_student_number'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['stream', 'status'], name='idx_student_stream_status'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['year_of_entry'], name='idx_student_year'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['full_name'], name='idx_student_name'),
        ),
    ]
