# Generated by Django 6.0.6 on 2026-06-24 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('students', '0002_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['student', 'date'], name='idx_attendance_student_date'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['stream', 'date'], name='idx_attendance_stream_date'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['date'], name='idx_attendance_date'),
        ),
    ]
