# Generated by Django 6.0.3 on 2026-06-23 14:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeOfWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.CharField(max_length=20)),
                ('week', models.PositiveIntegerField()),
                ('period', models.PositiveIntegerField(default=1)),
                ('theme_topic', models.CharField(max_length=500)),
                ('competency', models.TextField()),
                ('learning_outcomes', models.TextField()),
                ('learning_activities', models.TextField()),
                ('teaching_resources', models.TextField(blank=True)),
                ('references', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('assessment_methods', models.TextField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Revision Requested', 'Revision Requested')], default='Draft', max_length=25)),
                ('submitted_to', models.CharField(blank=True, max_length=30)),
                ('submitted_date', models.DateField(blank=True, null=True)),
                ('reviewed_date', models.DateField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='students.stream')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='staff.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schemes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('term', models.CharField(max_length=20)),
                ('week', models.PositiveIntegerField()),
                ('periods', models.PositiveIntegerField(default=1)),
                ('topic', models.CharField(max_length=500)),
                ('competencies', models.TextField()),
                ('learning_outcomes', models.TextField()),
                ('indicators', models.TextField()),
                ('values', models.TextField()),
                ('generic_skills', models.TextField()),
                ('introduction', models.TextField()),
                ('teacher_activities', models.TextField()),
                ('learner_activities', models.TextField()),
                ('main_activity', models.TextField()),
                ('assessment', models.TextField()),
                ('reflection', models.TextField(blank=True)),
                ('homework', models.TextField(blank=True)),
                ('teaching_materials', models.TextField(blank=True)),
                ('references', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Revision Requested', 'Revision Requested')], default='Draft', max_length=25)),
                ('submitted_to', models.CharField(blank=True, max_length=30)),
                ('submitted_date', models.DateField(blank=True, null=True)),
                ('reviewed_date', models.DateField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='students.stream')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='staff.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to='schemes.schemeofwork')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
