# Generated by Django 6.0.6 on 2026-06-24 13:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0002_alter_assessment_id_alter_mark_id_and_more'),
        ('staff', '0001_initial'),
        ('students', '0002_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinuousAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity1', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('activity2', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('project', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('grade', models.CharField(blank=True, max_length=15)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('is_submitted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddIndex(
            model_name='markssummary',
            index=models.Index(fields=['student', 'term'], name='idx_summary_student_term'),
        ),
        migrations.AddIndex(
            model_name='markssummary',
            index=models.Index(fields=['subject', 'term'], name='idx_summary_subject_term'),
        ),
        migrations.AddIndex(
            model_name='markssummary',
            index=models.Index(fields=['is_submitted'], name='idx_summary_submitted'),
        ),
        migrations.AddField(
            model_name='continuousassessment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ca_records', to='students.student'),
        ),
        migrations.AddField(
            model_name='continuousassessment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ca_records', to='staff.subject'),
        ),
        migrations.AddField(
            model_name='continuousassessment',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ca_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='continuousassessment',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ca_records', to='marks.term'),
        ),
        migrations.AlterUniqueTogether(
            name='continuousassessment',
            unique_together={('student', 'subject', 'term')},
        ),
    ]
