# Generated by hand: initial migration for sickbay app
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qualification', models.CharField(max_length=200)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('on_duty', models.BooleanField(default=True)),
                ('staff_profile', models.OneToOneField(on_delete=models.deletion.CASCADE, related_name='nurse_profile', to='staff.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SickbayVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time_in', models.TimeField(auto_now_add=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('complaint', models.TextField()),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
                ('medication_given', models.TextField(blank=True)),
                ('visit_type', models.CharField(default='outpatient', max_length=20, choices=[('outpatient', 'Outpatient'), ('admitted', 'Admitted'), ('referred', 'Referred to Hospital')])),
                ('referred_to', models.CharField(blank=True, max_length=200)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('attended_by', models.ForeignKey(null=True, on_delete=models.deletion.SET_NULL, related_name='sickbay_visits_attended', to='accounts.user')),
                ('student', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='sickbay_visits', to='students.student')),
            ],
            options={
                'ordering': ['-date', '-time_in'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_type', models.CharField(blank=True, max_length=5)),
                ('allergies', models.TextField(blank=True)),
                ('chronic_conditions', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(max_length=200)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('doctor_name', models.CharField(blank=True, max_length=200)),
                ('doctor_phone', models.CharField(blank=True, max_length=20)),
                ('insurance_provider', models.CharField(blank=True, max_length=200)),
                ('insurance_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('student', models.OneToOneField(on_delete=models.deletion.CASCADE, related_name='medical_record', to='students.student')),
            ],
        ),
    ]
